name: Deploy Playout FrontEnd

on:
  push:
    branches:
      - main

env:
  ENVIRONMENT: 'production'
  AZURE_WEBAPP_NAME: 'playout-frontend'
  AZURE_WEBAPP_PATH: '.'
  NODE_VERSION: '16.13.1'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login via AZURE CLI
        uses: azure/login@v1
        with:
          creds: ${{ secret.AZURE_CREDENTIALS }}

      - name: Setup Node.JS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install and Build Playout
      - run: |
          yarn install
          yarn build

      - name: Deploy in Azure App Service
        uses: azure/webapp-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: '${{ env.AZURE_WEBAPP_PATH }}'
